// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Uiwk3YbRO-cEgeiQCeZF_5JX_YZm3FM',
    appId: '1:737029007501:web:68c80019cb5ef72b459ac4',
    messagingSenderId: '737029007501',
    projectId: 'flash-chat-8399d',
    authDomain: 'flash-chat-8399d.firebaseapp.com',
    storageBucket: 'flash-chat-8399d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOoHV05iB4yt5Hbn2TVMiqoJR9KbmlmBY',
    appId: '1:737029007501:android:3417bf4be1b2dc53459ac4',
    messagingSenderId: '737029007501',
    projectId: 'flash-chat-8399d',
    storageBucket: 'flash-chat-8399d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEM0f_Ixzc7bpH2-Z3bq4bGZ76J5b2orU',
    appId: '1:737029007501:ios:9eea1c32857e98a7459ac4',
    messagingSenderId: '737029007501',
    projectId: 'flash-chat-8399d',
    storageBucket: 'flash-chat-8399d.appspot.com',
    iosBundleId: 'com.example.chats',
  );
}
